image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

before_script:
  - mkdir -p /home/gitlab-runner/.docker
  - echo -n > /home/gitlab-runner/.docker/ca.pem # 빈 인증서 파일 생성 (문제가 지속될 경우)

build:
  stage: build
  script:
    - docker info
    - docker build -t my-java-app .
    - docker run -d --name my-running-app my-java-app
