image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-java-app .
    - docker run -d --name my-running-app my-java-app
