image: openjdk:17-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test


build:
  stage: build
  image: gradle:7.6-jdk17
  before_script:
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle wrapper
    - ./gradlew assemble
    - ls
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
    expire_in: 1 week