stages:
  - build

before_script:
  - docker info

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-java-app .
    - docker run -d --name my-running-app my-java-app
